config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :categorys do
    resources :transactions
  end

  root "categorys#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :categories
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    if user_signed_in?
      @category = Category.all
      @total_category_transactions = Category.includes(:transactions).where(user_id: current_user.id).sum(:amount)
      @transactions = Category.includes(:transactions).where(id: :category_id).sum(:amount)
    else
      render '/splash/welcome'
    end
  end

  def show
    @category = Category.find(params[:id])
    @transactions = Transaction.where(category_id: params[:id])
    @total_transactions = @transactions.sum(:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    @category.user = current_user

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to category_transaction_url(id: @transaction.id), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categorys/_form.html.erb
<%= form_with url: categorys_path, scope: :category do |f|%>
<div>
 <%= f.label :name%>
 <%= f.text_field :name, class: 'w-full border border-gray-200 py-2'%>
</div>

<div>
 <%= f.label :icon%>
 <%= f.text_field :icon, class: 'w-full border border-gray-200 py-2'%>
</div>

 <%= f.submit  class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>
<% end %>

app/views/categorys/edit.html.erb
<h1>Categorys#edit</h1>
<p>Find me in app/views/categorys/edit.html.erb</p>
<%= render "form"%>

app/views/categorys/index.html.erb
<h1 class="text-4xl text-center m-2">Total Transaction for All Categories: $<%=@total_category_transactions%></h1>
<div class="grid md:gap-4 md:grid-cols-3 p-2 lg:grid-cols-3 ">
  <% @category.each do |category|%>
  <div class="border border-red-200 shadow-xl rounded-lg p-4 my- mx-2">
 <img class="w-[80%] h-[40%]" src="<%= category.icon%>" alt="...">
 <h1 class="text-2xl font-bold m-4"><%= link_to category.name, category_path(category.id)%></h1>
  <%= link_to "View",  category_path(category.id), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
  </div>
<% end%>
</div>

<div class="mt-2">
<%= link_to "Add New Category", new_category_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded ml-8"%>
</div>

app/views/categorys/new.html.erb
<div class="border border-gray-100 p-8">
<h1 class="text-4xl text-blue m-2 pb-4">Add Category</h1>
<button class="bg-slate-500 hover:bg-green-700 text-white font-bold py-2 px-8 rounded ml-8 mb-2">
<%= link_to "Back",  categorys_path%>
</button>
<%= render "form"%>
</div>

app/views/categorys/show.html.erb
<div class="border border-slate-200 p-8">
 <h3 class="text-4xl mb-4" >Great job. You have tracked $<%= @total_transactions%> of category <%= @category.name%></h3>
<img class="w-[40%] h-[10%]" src="<%= @category.icon%>" alt="...">
<h3 class="text-2xl m-2"><%= @category.name%></h3>
<% if @transactions.exists?%>
  <% @transactions.each do |t| %>
     <div class="bg-gray-100 w-[50%] p-4 m-2 rounded-sm">
     <p><strong>Transaction Name:</strong> <%=t.name%></p>
     <p><strong>Transaction Amount:</strong> <%= t.amount%></p>
     </div>
  <% end%>
<% else%>
<p>No Transaction Done</p>
<% end%>
<div class="grid w-[30%]">
<%= link_to "Back", categorys_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4" %>
<%= link_to "Add Transaction", new_category_transaction_path(@category), class: "bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% if user_signed_in?%>
       <%= render "shared/header"%>
       <%= yield %>
      <%else%>
      <%= yield %>
      <% end%>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="bg-blue-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>

        
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
       
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
      
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <a href="/categorys" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">BudgetTracker</a>
            <a href="/categorys" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">All Categories</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
        </button>

        <div class="ml-3 relative">
          <div>
         <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            <% if user_signed_in?%>
            <%=current_user.email %>
             <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% else%>
            <%= link_to "Sign In", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end%>
            </a>
          </div>


        </div>
      </div>
    </div>
  </div>


  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <a href="/categorys" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">BudgetTracker</a>

      <a href="/categorys" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">All Categories</a>

 <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
            <% if user_signed_in?%>
            <%=current_user.email %>
            <% else%>
            <%= link_to "Sign In", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end%>
            </a>
    </div>
  </div>
</nav>

app/views/splash/welcome.html.erb
<h1 class="text-6xl p-2 mt-2 text-center ">Welcome to BudgetTracker App</h1>
<div class="w-[95%] mx-auto m-6 p-4 bg-gray-100 rounded-lg">
<div class="text-center border border-gray-200 p-16 grid">
    <%= link_to "Login", new_user_session_path, class: "w-[40%] mx-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
    <p class="p-4">Or</p>
    <%= link_to "Sign Up", new_user_registration_path, class: "w-[40%] mx-auto bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
<div>
</div>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, url: category_transactions_path) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="w-[80%] border border-slate-200 mx-auto my-4" >
  <div class="p-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'w-full border border-gray-200 py-2' %>
  </div>

   <div class="p-2">
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount, class: 'w-full border border-gray-200 py-2' %>
  </div>

    <div class="p-2">
   
    <%= form.hidden_field :category_id, value: params[:category_id]%>
  </div>

  <div class="bg-slate-500 hover:bg-green-700 text-white font-bold py-2 px-8 rounded mb-2">
    <%= form.submit%>
  </div>
 </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="w-[80%] p-4 border border-gray-200 mx-auto">
  <p>
    <strong>Name:</strong>
    <%= transaction.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>
  <p>
  <strong>Category:</strong>
  <%= transaction.category.name%>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4" %> 
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="transactions" class="mt-8 mb-4">
<button class="bg-slate-500 hover:bg-green-700 text-white font-bold py-2 px-8 rounded ml-8 mb-2">
<%= link_to "Back",  categorys_path%>
</button>
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p class="m-4">
      <%= link_to "Show this transaction", category_transaction_path(id: transaction.id), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-8" %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_category_transaction_path, class: "bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4" %>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", category_transactions_path, class: "bg-blue-500 hover:bg-gray text-black font-bold py-2 px-4 rounded ml-8" %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
 <button class="bg-slate-500 hover:bg-green-700 text-white font-bold py-2 px-8 rounded ml-8 mb-2">
<%= link_to "Back",  categorys_path%>
</button>

</div>